@startuml d1
!pragma layout smetana
/' 
!theme materia
!theme cerulean
!theme cyborg
!theme silver
!theme sandstone
!theme sketchy
!theme spacelab
!theme bluegray
 '/
!theme materia

component asciidoctorj as adj
component docToolChain as dtc

file AsciiDoc as input
file html
file pdf
file confluence
file many_more

input -> adj
adj -> dtc : "html,\ndocbook"

adj --> html
adj --> pdf

dtc --> confluence
dtc --> many_more

@enduml
