= AsciiDoc Server

== Purpose

A SpringBoot application serving AsciiDoc documents as HTML 5.

== Examples

The examples below demonstrate the functionality of this application:

=== AsciiDoc Quick Reference
This is the official Quick reference composed of dozens of adoc snippets. All files are hosted locally. +
link:./quickref/asciidoc-syntax-quick-reference.adoc[AsciiDoc Quick Reference]

=== AsciiDoc Diagrams
This is a collection of diagrams with enhanced styling over the defaults.
Diagrams are simple ASCII definitions and rendered directly using the AsciiDoc Diagrams library. +
link:./asciidoc-diagrams.adoc[AsciiDoc Diagrams]

=== AsciiDoc Example
This example showcases a few features of AsciiDoc. +
link:./example/asciidoc-example.adoc[AsciiDoc Example]


== Links
=== Skins
https://github.com/darshandsoni/asciidoctor-skins +
https://darshandsoni.com/asciidoctor-skins/

=== Instructions
https://mrhaki.blogspot.com/2016/10/awesome-asciidoctor-source-syntax.html
https://mrhaki.blogspot.com/2019/03/awesome-asciidoctor-collapsible-content.html
https://blog.jdriven.com/2019/04/awesome-asciidoctor-collapsible-content/

https://blog.arkey.fr/2020/04/23/tackling-hugo-integration-of-asciidoctor/
https://jshingler.github.io/blog/2019/12/07/creating-this-site/
https://mrhaki.blogspot.com/2017/10/awesome-asciidoctor-use-diagram-block.html
http://tscanlin.github.io/tocbot/

https://github.com/asciidoctor/docgist +
https://github.com/Mogztter/asciidoctor-kroki +
https://www.asciidocfx.com/ +
https://plantuml.com/sequence-diagram +
https://www.programcreek.com/java-api-examples/?api=org.asciidoctor.Asciidoctor
https://github.com/RicardoNiepel/C4-PlantUML

https://plantuml.com/de/vizjs
